#include "Zombie.hpp"

Zombie* zombieHorde( int N, std::string name )
{
    Zombie *z_ptr = new Zombie [N];

    for (int i = 0; i < N; i++)
    {
        // copy assignment or assignment operator overload : generated by the compiler if not defined
        z_ptr[i] = Zombie(name + (char)(48 + i));
    }
    return (z_ptr);
}